### ISSUE TITLE
min/max constraints cause out of bounds freezing

### ISSUE THREAD

**Issue by isusanin** [cdglabs/apparatus#18] opened 2015-10-06 22:12 UTC
Steps to reproduce:
1) create a circle at (0, 0)
2) create a variable called slider and initialize to 0.0
3) set X of circle to min(5.0, max(0.0, slider))
4) Set control of circle to X/slider

Now drag the circle quickly. You'll notice that you can easily get the slider value below 0.0 or above 5.0, violating the constraint. When this happens, the circle also gets stuck and you can't drag it anymore.

**Comment by electronicwhisper** [comment] 2015-10-07 20:02
I'm going to mark this a duplicate of issue #12, constraining variables within bounds.

**Closed as completed by electronicwhisper** 2015-10-07 20:02 UTC
